// Setup
// Get the page elements and the canvas drawing context.
const canvas = document.getElementById("gameCanvas");
const ctx = canvas.getContext("2d");
const scoreDisplay = document.getElementById("scoreDisplay");
const highScoreDisplay = document.getElementById("highScoreDisplay");
const levelDisplay = document.getElementById("levelDisplay");
const livesDisplay = document.getElementById("livesDisplay");
const muteButton = document.getElementById("muteButton");
const pauseButton = document.getElementById("pauseButton");
const actionButton = document.getElementById("actionButton");
const hintText = document.getElementById("hintText");

// Tuning values
// Sound config. These use the browser's Web Audio API, so no sound files are needed.
let audioContext = null;
let isMuted = false;

// Ball config.
const ballRadius = 14;
const ballStartX = canvas.width / 2;
const ballStartY = canvas.height - 80;
const ballStartSpeedX = 6;
const ballStartSpeedY = -6;
const maxBallSpeed = 12;
let ballX = ballStartX;
let ballY = ballStartY;
let ballSpeedX = ballStartSpeedX;
let ballSpeedY = ballStartSpeedY;

// Paddle config.
const paddleHeight = 18;
const normalPaddleWidth = 160;
const widePaddleWidth = 240;
const paddleY = canvas.height - paddleHeight - 24;
const paddleSpeed = 12;
let paddleWidth = normalPaddleWidth;
let paddleX = (canvas.width - paddleWidth) / 2;

// Powerup config.
const powerupSize = 24;
const powerupSpeed = 4;
const widePaddleDropChance = 0.3;
const extraLifeDropChance = 0.15;
const powerupDuration = 5000;
let powerups = [];
let paddlePowerupEndTime = 0;

// Simple visual effects. These arrays stay small and old items are removed
// as soon as they fade out, which keeps performance reasonable on phones.
const particlesPerBrick = 10;
const maxParticles = 120;
const floatingTextLifetime = 650;
const brickScoreValue = 1;
let particles = [];
let floatingTexts = [];
let lastFrameTime = 0;

// These remember whether the player is holding an arrow key down.
let rightPressed = false;
let leftPressed = false;

// Brick and level layout config.
const baseBrickRows = 5;
const maxBrickRows = 8;
const brickColumns = 10;
const brickWidth = 72;
const brickHeight = 28;
const brickPadding = 12;
const brickOffsetTop = 82;
const brickWallWidth = brickColumns * brickWidth + (brickColumns - 1) * brickPadding;
const brickOffsetLeft = (canvas.width - brickWallWidth) / 2;
const minVisibleBricks = 10;
const brickColors = ["#ef4444", "#f97316", "#facc15", "#22c55e", "#38bdf8", "#a78bfa", "#fb7185"];
const layoutTypes = [
  "fullGrid",
  "checkerboard",
  "pyramid",
  "diamond",
  "border",
  "columns",
  "stripes",
  "staggered",
  "randomGaps",
  "cross"
];

let score = 0;
const highScoreStorageKey = "neonBrickRallyHighScore";
let highScore = loadHighScore();
let lives = 3;
let level = 1;
const maxLives = 5;
const maxLevel = 50;
let bricksRemaining = 0;
const levelDelayDuration = 5000;
let levelCountdownEndTime = 0;
let pauseStartedAt = 0;

// The game state tells the loop what should happen right now.
// Possible states are "start", "playing", "paused", "levelTransition", "gameOver", and "win".
let gameState = "start";

// The current level's bricks are generated by createLevel().
let bricks = [];

// Input
// Listen for key presses so the paddle can move while a key is held down.
// Using window helps the game catch arrow keys as long as the page is active.
window.addEventListener("keydown", handleKeyDown);
window.addEventListener("keyup", handleKeyUp);
canvas.addEventListener("click", handleCanvasClick);
canvas.addEventListener("mousemove", handleMouseMove);
canvas.addEventListener("touchstart", handleCanvasTouchStart, { passive: false });
canvas.addEventListener("touchmove", handleTouchMove, { passive: false });
muteButton.addEventListener("click", handleMuteClick);
pauseButton.addEventListener("click", handlePauseButtonClick);
actionButton.addEventListener("click", handleActionButtonClick);

function handleKeyDown(event) {
  unlockAudio();

  if (isPauseKey(event)) {
    event.preventDefault();
    togglePause();
  } else if (isRightArrow(event)) {
    event.preventDefault();
    rightPressed = true;
  } else if (isLeftArrow(event)) {
    event.preventDefault();
    leftPressed = true;
  } else if (event.key === " ") {
    event.preventDefault();

    // Space keeps the original desktop start/restart behavior.
    startOrRestartGame();
  }
}

function handleKeyUp(event) {
  if (isRightArrow(event)) {
    event.preventDefault();
    rightPressed = false;
  } else if (isLeftArrow(event)) {
    event.preventDefault();
    leftPressed = false;
  }
}

function isRightArrow(event) {
  return event.key === "Right" || event.key === "ArrowRight" || event.code === "ArrowRight";
}

function isLeftArrow(event) {
  return event.key === "Left" || event.key === "ArrowLeft" || event.code === "ArrowLeft";
}

function isPauseKey(event) {
  return event.key === "p" || event.key === "P" || event.code === "KeyP";
}

function handleCanvasClick() {
  unlockAudio();

  // A mouse click or mobile-generated click on the canvas can start/restart
  // only from screens that are waiting for the player.
  startOrRestartGame();
}

function handleMouseMove(event) {
  unlockAudio();

  if (!canMovePaddleWithPointer()) {
    return;
  }

  // Mouse control: place the paddle center under the mouse while it is over the canvas.
  movePaddleToCanvasX(event.clientX);
}

function handleCanvasTouchStart(event) {
  unlockAudio();
  event.preventDefault();

  // On phones, the first tap on the start/restart screens should only change
  // the game state. It should not also jump the paddle to the tap position.
  if (isWaitingForStartOrRestart()) {
    startOrRestartGame();
    return;
  }

  if (event.touches.length > 0 && canMovePaddleWithPointer()) {
    movePaddleToCanvasX(event.touches[0].clientX);
  }
}

function handleTouchMove(event) {
  unlockAudio();

  // Touch control: use the first finger to move the paddle on phones and tablets.
  event.preventDefault();

  if (event.touches.length > 0 && canMovePaddleWithPointer()) {
    movePaddleToCanvasX(event.touches[0].clientX);
  }
}

function handleActionButtonClick() {
  unlockAudio();
  startOrRestartGame();
}

function handlePauseButtonClick() {
  unlockAudio();
  togglePause();
}

function isWaitingForStartOrRestart() {
  return gameState === "start" || gameState === "gameOver" || gameState === "win";
}

function canMovePaddleWithPointer() {
  return gameState === "playing" || gameState === "levelTransition";
}

function togglePause() {
  // Pausing is only for active gameplay. It does not start from the opening
  // screen, and it does not restart after game over or winning.
  if (gameState === "playing") {
    pauseGame();
  } else if (gameState === "paused") {
    resumeGame();
  }
}

function pauseGame() {
  gameState = "paused";
  pauseStartedAt = Date.now();

  // Stop keyboard paddle movement immediately if an arrow key is held down.
  rightPressed = false;
  leftPressed = false;
}

function resumeGame() {
  const pausedDuration = Date.now() - pauseStartedAt;

  // Wide-paddle powerups use a Date.now() end time. Push that end time forward
  // so the remaining powerup time is unchanged by pausing.
  if (paddleWidth === widePaddleWidth && paddlePowerupEndTime > 0) {
    paddlePowerupEndTime += pausedDuration;
  }

  pauseStartedAt = 0;
  gameState = "playing";
}

function startOrRestartGame() {
  // Start from the opening screen. Restart only after game over or after winning.
  if (gameState === "start") {
    gameState = "playing";
  } else if (gameState === "gameOver" || gameState === "win") {
    resetGame();
  }
}

function handleMuteClick() {
  unlockAudio();
  isMuted = !isMuted;
  muteButton.textContent = isMuted ? "Sound Off" : "Sound On";
  muteButton.setAttribute("aria-pressed", String(isMuted));
}

function movePaddleToCanvasX(clientX) {
  const canvasBounds = canvas.getBoundingClientRect();
  const scaleX = canvas.width / canvasBounds.width;
  const pointerX = (clientX - canvasBounds.left) * scaleX;

  // Center the paddle on the pointer and clamp it inside the canvas.
  paddleX = clampPaddleX(pointerX - paddleWidth / 2);
}

function clampPaddleX(nextPaddleX) {
  return Math.max(0, Math.min(nextPaddleX, canvas.width - paddleWidth));
}

function unlockAudio() {
  // Browsers usually require a user action before sounds can play.
  const context = getAudioContext();

  if (context && context.state === "suspended") {
    context.resume().catch(function () {
      // If the browser blocks audio, keep the game running without sound.
    });
  }
}

function getAudioContext() {
  const AudioContextClass = window.AudioContext || window.webkitAudioContext;

  // If Web Audio is not supported, return null and let the game continue silently.
  if (!AudioContextClass) {
    return null;
  }

  if (!audioContext) {
    try {
      audioContext = new AudioContextClass();
    } catch (error) {
      return null;
    }
  }

  return audioContext;
}

function playTone(frequency, duration, type = "square", volume = 0.05, delay = 0) {
  if (isMuted) {
    return;
  }

  const context = getAudioContext();

  // If audio is unavailable or still blocked, skip the sound without breaking gameplay.
  if (!context || context.state !== "running") {
    return;
  }

  const startTime = context.currentTime + delay;
  try {
    const oscillator = context.createOscillator();
    const gain = context.createGain();

    oscillator.type = type;
    oscillator.frequency.setValueAtTime(frequency, startTime);
    gain.gain.setValueAtTime(volume, startTime);
    gain.gain.exponentialRampToValueAtTime(0.001, startTime + duration);

    oscillator.connect(gain);
    gain.connect(context.destination);
    oscillator.start(startTime);
    oscillator.stop(startTime + duration);
  } catch (error) {
    // Audio errors should never stop the game.
  }
}

function playSound(soundName) {
  // Each sound is just one or more short tones.
  if (soundName === "paddle") {
    playTone(360, 0.08, "square", 0.04);
  } else if (soundName === "brick") {
    playTone(620, 0.07, "triangle", 0.05);
  } else if (soundName === "loseLife") {
    playTone(180, 0.18, "sawtooth", 0.05);
  } else if (soundName === "gameOver") {
    playTone(220, 0.14, "sawtooth", 0.05);
    playTone(140, 0.2, "sawtooth", 0.05, 0.12);
  } else if (soundName === "win") {
    playTone(523, 0.1, "triangle", 0.05);
    playTone(659, 0.1, "triangle", 0.05, 0.12);
    playTone(784, 0.16, "triangle", 0.05, 0.24);
  }
}

// Drawing
function drawBall() {
  ctx.beginPath();
  ctx.arc(ballX, ballY, ballRadius, 0, Math.PI * 2);
  ctx.fillStyle = "#facc15";
  ctx.fill();
  ctx.closePath();
}

function drawPaddle() {
  ctx.beginPath();
  ctx.rect(paddleX, paddleY, paddleWidth, paddleHeight);
  ctx.fillStyle = "#22c55e";
  ctx.fill();
  ctx.closePath();
}

function drawPowerups() {
  // Powerups are small falling squares. Different colors mean different effects.
  for (const powerup of powerups) {
    ctx.beginPath();
    ctx.rect(powerup.x, powerup.y, powerup.width, powerup.height);
    ctx.fillStyle = powerup.type === "extraLife" ? "#22d3ee" : "#c084fc";
    ctx.fill();
    ctx.strokeStyle = "#f5d0fe";
    ctx.lineWidth = 2;
    ctx.stroke();
    ctx.closePath();

    if (powerup.type === "extraLife") {
      ctx.font = "14px Arial";
      ctx.fillStyle = "#082f49";
      ctx.fillText("+1", powerup.x + 4, powerup.y + 17);
    }
  }
}

function drawBricks() {
  // Loop through every column and row in the brick grid.
  for (let column = 0; column < bricks.length; column++) {
    for (let row = 0; row < bricks[column].length; row++) {
      const brick = bricks[column][row];

      // Only draw bricks that are still visible.
      if (brick.visible) {
        ctx.beginPath();
        ctx.rect(brick.x, brick.y, brick.width, brick.height);
        ctx.fillStyle = brick.color;
        ctx.fill();

        // Bricks with 2 hits left get a dark border. After one hit, the border disappears.
        if (brick.hitsRemaining > 1) {
          ctx.lineWidth = 3;
          ctx.strokeStyle = "#020617";
          ctx.stroke();
        }

        ctx.closePath();
      }
    }
  }
}

function getBrickColor(row) {
  return brickColors[row % brickColors.length];
}

function drawScore() {
  ctx.font = "24px Arial";
  ctx.fillStyle = "#f8fafc";
  ctx.fillText(`Score: ${score}`, 24, 36);
}

function drawLevel() {
  ctx.font = "24px Arial";
  ctx.fillStyle = "#f8fafc";
  ctx.fillText(`Level: ${level}`, canvas.width / 2 - 44, 36);
}

function updateScoreDisplay() {
  // Keep the HTML score display in sync with the score variable.
  scoreDisplay.textContent = score;

  // If this run beats the saved high score, remember it right away.
  if (score > highScore) {
    updateHighScore(score);
  }
}

function updateHighScoreDisplay() {
  // Keep the HTML high score display in sync with the highScore variable.
  highScoreDisplay.textContent = highScore;
}

function loadHighScore() {
  // localStorage can be blocked in some browser privacy modes. If anything
  // goes wrong, use an in-memory high score so the game still works.
  try {
    const savedHighScore = window.localStorage.getItem(highScoreStorageKey);
    const parsedHighScore = Number.parseInt(savedHighScore, 10);

    if (Number.isFinite(parsedHighScore) && parsedHighScore > 0) {
      return parsedHighScore;
    }
  } catch (error) {
    // Ignore storage errors and fall back to 0.
  }

  return 0;
}

function saveHighScore() {
  // Saving should never interrupt gameplay, even if storage is unavailable.
  try {
    window.localStorage.setItem(highScoreStorageKey, String(highScore));
  } catch (error) {
    // Keep the in-memory high score for this browser session.
  }
}

function updateHighScore(nextHighScore) {
  highScore = nextHighScore;
  updateHighScoreDisplay();
  saveHighScore();
}

function updateLivesDisplay() {
  // Keep the HTML lives display in sync with the lives variable.
  livesDisplay.textContent = lives;
}

function updateLevelDisplay() {
  // Keep the HTML level display in sync with the level variable.
  levelDisplay.textContent = level;
}

function drawLives() {
  ctx.font = "24px Arial";
  ctx.fillStyle = "#f8fafc";
  ctx.fillText(`Lives: ${lives}`, canvas.width - 120, 36);
}

function drawStartScreen() {
  // The start state pauses movement until the player presses Space, taps,
  // clicks the canvas, or uses the visible Start button.
  ctx.font = "36px Arial";
  ctx.fillStyle = "#f8fafc";
  ctx.textAlign = "center";
  ctx.fillText("Press Space or Tap to Start", canvas.width / 2, canvas.height / 2);
  ctx.font = "24px Arial";
  ctx.fillText(`High Score: ${highScore}`, canvas.width / 2, canvas.height / 2 + 42);
  ctx.textAlign = "left";
}

function drawLevelCountdownScreen() {
  // Between levels, pause the ball and show a simple countdown.
  const timeLeft = Math.ceil((levelCountdownEndTime - Date.now()) / 1000);

  ctx.fillStyle = "#f8fafc";
  ctx.textAlign = "center";

  ctx.font = "36px Arial";
  ctx.fillText(`Level ${level}`, canvas.width / 2, canvas.height / 2 - 28);

  ctx.font = "24px Arial";
  ctx.fillText(`Starting in ${Math.max(timeLeft, 1)}...`, canvas.width / 2, canvas.height / 2 + 24);

  ctx.textAlign = "left";
}

function drawGameOverScreen() {
  // The game over state shows the player's final score and waits for restart input.
  ctx.fillStyle = "#f8fafc";
  ctx.textAlign = "center";

  ctx.font = "42px Arial";
  ctx.fillText("Game Over", canvas.width / 2, canvas.height / 2 - 32);

  ctx.font = "24px Arial";
  ctx.fillText(`Final Score: ${score}`, canvas.width / 2, canvas.height / 2 + 14);
  ctx.fillText(`High Score: ${highScore}`, canvas.width / 2, canvas.height / 2 + 50);
  ctx.fillText("Press Space or Tap to Restart", canvas.width / 2, canvas.height / 2 + 90);

  ctx.textAlign = "left";
}

function drawWinScreen() {
  // The win state shows the final score and waits for restart input.
  ctx.fillStyle = "#f8fafc";
  ctx.textAlign = "center";

  ctx.font = "42px Arial";
  ctx.fillText("You Win!", canvas.width / 2, canvas.height / 2 - 32);

  ctx.font = "24px Arial";
  ctx.fillText(`Final Score: ${score}`, canvas.width / 2, canvas.height / 2 + 14);
  ctx.fillText(`High Score: ${highScore}`, canvas.width / 2, canvas.height / 2 + 50);
  ctx.fillText("Press Space or Tap to Restart", canvas.width / 2, canvas.height / 2 + 90);

  ctx.textAlign = "left";
}

function drawPausedScreen() {
  // Keep the current gameplay frame visible, then dim it with a pause message.
  ctx.fillStyle = "rgba(2, 6, 23, 0.62)";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  ctx.fillStyle = "#f8fafc";
  ctx.textAlign = "center";
  ctx.font = "42px Arial";
  ctx.fillText("Paused", canvas.width / 2, canvas.height / 2 - 12);

  ctx.font = "24px Arial";
  ctx.fillText("Press P or tap Resume", canvas.width / 2, canvas.height / 2 + 34);
  ctx.textAlign = "left";
}

function updateActionControls() {
  if (gameState === "start") {
    actionButton.hidden = false;
    actionButton.textContent = "Start";
    hintText.textContent = "Press Space or Tap to Start. Move with arrow keys, mouse, or touch.";
  } else if (gameState === "gameOver" || gameState === "win") {
    actionButton.hidden = false;
    actionButton.textContent = "Restart";
    hintText.textContent = "Press Space or Tap to Restart.";
  } else if (gameState === "paused") {
    actionButton.hidden = true;
    hintText.textContent = "Paused. Press P or tap Resume.";
  } else {
    actionButton.hidden = true;
    hintText.textContent = "Move with arrow keys, mouse, or touch. Press P or tap Pause.";
  }
}

function updatePauseControl() {
  if (gameState === "paused") {
    pauseButton.disabled = false;
    pauseButton.textContent = "Resume";
  } else if (gameState === "playing") {
    pauseButton.disabled = false;
    pauseButton.textContent = "Pause";
  } else {
    pauseButton.disabled = true;
    pauseButton.textContent = "Pause";
  }
}

function spawnBrickParticles(brick) {
  // Particles start from the broken brick's center and fly outward.
  const centerX = brick.x + brick.width / 2;
  const centerY = brick.y + brick.height / 2;

  for (let count = 0; count < particlesPerBrick; count++) {
    const angle = Math.random() * Math.PI * 2;
    const speed = 0.08 + Math.random() * 0.14;

    particles.push({
      x: centerX,
      y: centerY,
      size: 3 + Math.random() * 3,
      color: brick.color,
      vx: Math.cos(angle) * speed,
      vy: Math.sin(angle) * speed,
      age: 0,
      lifetime: 400 + Math.random() * 300
    });
  }

  // If many bricks break quickly, trim the oldest particles first.
  if (particles.length > maxParticles) {
    particles.splice(0, particles.length - maxParticles);
  }
}

function updateParticles(deltaTime) {
  // Move particles and age them. Loop backward so removal is safe.
  for (let index = particles.length - 1; index >= 0; index--) {
    const particle = particles[index];
    particle.x += particle.vx * deltaTime;
    particle.y += particle.vy * deltaTime;
    particle.age += deltaTime;

    if (particle.age >= particle.lifetime) {
      particles.splice(index, 1);
    }
  }
}

function drawParticles() {
  for (const particle of particles) {
    const alpha = 1 - particle.age / particle.lifetime;

    ctx.globalAlpha = Math.max(alpha, 0);
    ctx.fillStyle = particle.color;
    ctx.fillRect(particle.x, particle.y, particle.size, particle.size);
  }

  ctx.globalAlpha = 1;
}

function spawnFloatingText(text, x, y) {
  // Floating score labels rise slowly and fade out near the broken brick.
  floatingTexts.push({
    text: text,
    x: x,
    y: y,
    vy: -0.06,
    age: 0,
    lifetime: floatingTextLifetime
  });
}

function updateFloatingTexts(deltaTime) {
  for (let index = floatingTexts.length - 1; index >= 0; index--) {
    const floatingText = floatingTexts[index];
    floatingText.y += floatingText.vy * deltaTime;
    floatingText.age += deltaTime;

    if (floatingText.age >= floatingText.lifetime) {
      floatingTexts.splice(index, 1);
    }
  }
}

function drawFloatingTexts() {
  ctx.font = "20px Arial";
  ctx.textAlign = "center";

  for (const floatingText of floatingTexts) {
    const alpha = 1 - floatingText.age / floatingText.lifetime;

    ctx.globalAlpha = Math.max(alpha, 0);
    ctx.fillStyle = "#facc15";
    ctx.fillText(floatingText.text, floatingText.x, floatingText.y);
  }

  ctx.globalAlpha = 1;
  ctx.textAlign = "left";
}

function clearEffects() {
  particles = [];
  floatingTexts = [];
}

// Collision
function checkBrickCollisions() {
  for (let column = 0; column < bricks.length; column++) {
    for (let row = 0; row < bricks[column].length; row++) {
      const brick = bricks[column][row];

      // Skip bricks that have already been hit and hidden.
      if (!brick.visible) {
        continue;
      }

      const ballLeft = ballX - ballRadius;
      const ballRight = ballX + ballRadius;
      const ballTop = ballY - ballRadius;
      const ballBottom = ballY + ballRadius;
      const brickRight = brick.x + brick.width;
      const brickBottom = brick.y + brick.height;

      // Check whether the ball's circle overlaps this brick's rectangle.
      const isHittingBrick =
        ballRight > brick.x &&
        ballLeft < brickRight &&
        ballBottom > brick.y &&
        ballTop < brickBottom;

      if (isHittingBrick) {
        // Bounce the ball whenever it hits a brick.
        ballSpeedY = -ballSpeedY;
        playSound("brick");

        if (brick.hitsRemaining > 1) {
          // Two-hit bricks become normal one-hit bricks after the first hit.
          brick.hitsRemaining--;
          return;
        }

        // Hide one-hit bricks, add points, count one fewer brick, and show
        // small visual effects. These effects do not affect collision logic.
        brick.visible = false;
        score += brickScoreValue;
        bricksRemaining--;
        updateScoreDisplay();
        spawnBrickParticles(brick);
        spawnFloatingText(`+${brickScoreValue}`, brick.x + brick.width / 2, brick.y + brick.height / 2);
        maybeCreatePowerup(brick);

        // If every brick in this level is gone, move forward or finish the game.
        if (bricksRemaining === 0) {
          advanceToNextLevel();
        }

        // Stop after one brick hit so the bounce stays simple.
        return;
      }
    }
  }
}

function movePaddle() {
  // Move right, but stop when the paddle reaches the right edge.
  if (rightPressed && paddleX < canvas.width - paddleWidth) {
    paddleX = clampPaddleX(paddleX + paddleSpeed);
  } else if (leftPressed && paddleX > 0) {
    // Move left, but stop when the paddle reaches the left edge.
    paddleX = clampPaddleX(paddleX - paddleSpeed);
  }
}

function moveBall() {
  checkWallCollisions();

  if (!checkPaddleCollision() && ballY + ballSpeedY > canvas.height - ballRadius) {
    loseLife();
    return;
  }

  // Move the ball diagonally by changing both its x and y positions each frame.
  ballX += ballSpeedX;
  ballY += ballSpeedY;
}

// Powerups
function maybeCreatePowerup(brick) {
  // Even-numbered levels can drop +1 life powerups, capped at maxLives.
  if (level % 2 === 0 && lives < maxLives && Math.random() < extraLifeDropChance) {
    spawnPowerup("extraLife", brick);
    return;
  }

  // Any level can drop the wide-paddle powerup.
  if (Math.random() < widePaddleDropChance) {
    spawnPowerup("widePaddle", brick);
  }
}

function spawnPowerup(type, brick) {
  powerups.push({
    type: type,
    x: brick.x + brick.width / 2 - powerupSize / 2,
    y: brick.y + brick.height / 2,
    width: powerupSize,
    height: powerupSize
  });
}

function updatePowerups() {
  // Move powerups downward and check whether the paddle catches them.
  for (let index = powerups.length - 1; index >= 0; index--) {
    const powerup = powerups[index];
    powerup.y += powerupSpeed;

    if (isPowerupCaught(powerup)) {
      activatePowerup(powerup.type);
      powerups.splice(index, 1);
    } else if (powerup.y > canvas.height) {
      powerups.splice(index, 1);
    }
  }
}

function isPowerupCaught(powerup) {
  const powerupBottom = powerup.y + powerup.height;
  const powerupRight = powerup.x + powerup.width;
  const paddleRight = paddleX + paddleWidth;

  return (
    powerupBottom >= paddleY &&
    powerup.y <= paddleY + paddleHeight &&
    powerupRight >= paddleX &&
    powerup.x <= paddleRight
  );
}

function activatePowerup(type) {
  if (type === "extraLife") {
    activateExtraLife();
  } else {
    activateWidePaddle();
  }
}

function activateWidePaddle() {
  // Catching the powerup makes the paddle wider for a few seconds.
  paddleWidth = widePaddleWidth;
  paddlePowerupEndTime = Date.now() + powerupDuration;
  paddleX = clampPaddleX(paddleX);
}

function activateExtraLife() {
  // Extra-life powerups add one life, but never above the maximum.
  lives = Math.min(lives + 1, maxLives);
  updateLivesDisplay();
}

function updatePaddlePowerup() {
  // When the timer ends, return the paddle to its normal size.
  if (paddleWidth === widePaddleWidth && Date.now() >= paddlePowerupEndTime) {
    paddleWidth = normalPaddleWidth;
    paddleX = clampPaddleX(paddleX);
    paddlePowerupEndTime = 0;
  }
}

function clearPowerups() {
  powerups = [];
  paddleWidth = normalPaddleWidth;
  paddlePowerupEndTime = 0;
}

// Collision helpers
function checkWallCollisions() {
  const nextBallX = ballX + ballSpeedX;
  const nextBallY = ballY + ballSpeedY;

  // If the next ball position would hit a side wall, reverse the x speed.
  // Reversing x speed makes the ball bounce left or right.
  if (nextBallX > canvas.width - ballRadius || nextBallX < ballRadius) {
    ballSpeedX = -ballSpeedX;
  }

  // If the next ball position would hit the top wall, reverse the y speed.
  // Reversing y speed makes the ball bounce up or down.
  if (nextBallY < ballRadius) {
    ballSpeedY = -ballSpeedY;
  }
}

function checkPaddleCollision() {
  const nextBallY = ballY + ballSpeedY;
  const nextBallBottom = nextBallY + ballRadius;
  const isMovingDown = ballSpeedY > 0;
  const isOverPaddle = ballX > paddleX && ballX < paddleX + paddleWidth;
  const isTouchingPaddle = nextBallBottom >= paddleY && nextBallBottom <= paddleY + paddleHeight;

  // Only bounce from the paddle when the ball is moving downward and touches it.
  if (isMovingDown && isOverPaddle && isTouchingPaddle) {
    const paddleCenter = paddleX + paddleWidth / 2;
    const hitDistanceFromCenter = ballX - paddleCenter;

    // Divide by half the paddle width to get a simple number from about -1 to 1.
    // Left side hits make ballSpeedX negative, right side hits make it positive.
    const hitPercent = hitDistanceFromCenter / (paddleWidth / 2);
    ballSpeedX = hitPercent * 4;

    // Always send the ball upward after it hits the paddle.
    ballSpeedY = -Math.abs(ballSpeedY);
    playSound("paddle");
    return true;
  }

  return false;
}

// Levels
function resetBall() {
  const levelSpeed = getBallSpeedForLevel(level);

  ballX = ballStartX;
  ballY = ballStartY;
  ballSpeedX = levelSpeed;
  ballSpeedY = -levelSpeed;
}

function getBallSpeedForLevel(levelNumber) {
  // Increase speed every few levels, but cap it so the game stays playable.
  const speedIncrease = Math.floor((levelNumber - 1) / 3) * 0.35;
  return Math.min(ballStartSpeedX + speedIncrease, maxBallSpeed);
}

function resetBallAndPaddle() {
  // Put the ball and paddle back in their starting positions after a missed ball.
  resetBall();
  paddleX = (canvas.width - paddleWidth) / 2;
}

function loseLife() {
  // The player loses one life when the ball falls below the paddle.
  lives--;
  updateLivesDisplay();
  playSound("loseLife");

  if (lives === 0) {
    // With no lives left, stop gameplay and show the game over message.
    gameState = "gameOver";
    playSound("gameOver");
  } else {
    // If lives remain, reset the ball and paddle so the player can continue.
    resetBallAndPaddle();
  }
}

function resetGame() {
  // Restarting returns every important game value to its starting state.
  score = 0;
  updateScoreDisplay();
  lives = 3;
  updateLivesDisplay();
  level = 1;
  updateLevelDisplay();
  gameState = "playing";
  clearPowerups();
  clearEffects();
  createLevel(level);
  resetBallAndPaddle();
  rightPressed = false;
  leftPressed = false;
}

function createLevel(levelNumber) {
  // A level is generated from the level number instead of hand-coding 50 screens.
  const layoutType = getLayoutType(levelNumber);
  bricks = createBrickGrid(layoutType, levelNumber);
  bricksRemaining = countVisibleBricks();
  updateLevelDisplay();
}

function getLayoutType(levelNumber) {
  // Rotate through 10 reusable layout patterns:
  // level 1 full grid, level 2 checkerboard, ... level 10 cross, then repeat harder.
  const layoutIndex = (levelNumber - 1) % layoutTypes.length;
  return layoutTypes[layoutIndex];
}

function createBrickGrid(layoutType, levelNumber) {
  const rowCount = getRowCountForLevel(levelNumber);
  const newBricks = [];

  for (let column = 0; column < brickColumns; column++) {
    newBricks[column] = [];

    for (let row = 0; row < rowCount; row++) {
      const visible = isBrickVisibleForLayout(layoutType, row, column, rowCount, brickColumns, levelNumber);

      newBricks[column][row] = {
        x: column * (brickWidth + brickPadding) + brickOffsetLeft,
        y: row * (brickHeight + brickPadding) + brickOffsetTop,
        width: brickWidth,
        height: brickHeight,
        hitsRemaining: visible ? getBrickHitCount(row, column, levelNumber) : 1,
        color: getBrickColor(row),
        visible: visible
      };
    }
  }

  return ensureMinimumVisibleBricks(newBricks);
}

function getRowCountForLevel(levelNumber) {
  // Later levels add a couple of rows, but the bricks still stay above the paddle.
  return Math.min(baseBrickRows + Math.floor((levelNumber - 1) / 20), maxBrickRows);
}

function isBrickVisibleForLayout(layoutType, row, column, rowCount, columnCount, levelNumber) {
  const centerColumn = Math.floor(columnCount / 2);
  const centerRow = Math.floor(rowCount / 2);

  if (layoutType === "fullGrid") {
    return true;
  }

  if (layoutType === "checkerboard") {
    return (row + column) % 2 === 0;
  }

  if (layoutType === "pyramid") {
    return Math.abs(column - centerColumn) <= row;
  }

  if (layoutType === "diamond") {
    return Math.abs(row - centerRow) + Math.abs(column - centerColumn) <= centerRow;
  }

  if (layoutType === "border") {
    return row === 0 || row === rowCount - 1 || column === 0 || column === columnCount - 1;
  }

  if (layoutType === "columns") {
    return column % 2 === 0;
  }

  if (layoutType === "stripes") {
    return row % 2 === 0;
  }

  if (layoutType === "staggered") {
    return (column + row % 2) % 3 !== 0;
  }

  if (layoutType === "randomGaps") {
    return getDeterministicRandom(levelNumber, row, column) > 0.25;
  }

  if (layoutType === "cross") {
    return row === centerRow || column === centerColumn;
  }

  return true;
}

function getDeterministicRandom(levelNumber, row, column) {
  // This makes random-gap levels repeatable for a given level number.
  const value = Math.sin(levelNumber * 100 + row * 10 + column) * 10000;
  return value - Math.floor(value);
}

function getBrickHitCount(row, column, levelNumber) {
  // Later levels introduce more two-hit bricks. These draw with dark borders.
  if (levelNumber < 8) {
    return 1;
  }

  const difficultyBand = Math.floor((levelNumber - 1) / 10);
  const toughPattern = (row + column + levelNumber) % Math.max(5 - difficultyBand, 2);
  return toughPattern === 0 ? 2 : 1;
}

function ensureMinimumVisibleBricks(newBricks) {
  let visibleCount = countVisibleCells(newBricks);

  if (visibleCount >= minVisibleBricks) {
    return newBricks;
  }

  for (let column = 0; column < newBricks.length; column++) {
    for (let row = 0; row < newBricks[column].length; row++) {
      if (!newBricks[column][row].visible) {
        newBricks[column][row].visible = true;
        visibleCount++;
      }

      if (visibleCount >= minVisibleBricks) {
        return newBricks;
      }
    }
  }

  return newBricks;
}

function countVisibleCells(brickGrid) {
  let visibleCount = 0;

  for (let column = 0; column < brickGrid.length; column++) {
    for (let row = 0; row < brickGrid[column].length; row++) {
      if (brickGrid[column][row] && brickGrid[column][row].visible) {
        visibleCount++;
      }
    }
  }

  return visibleCount;
}

function countVisibleBricks() {
  return countVisibleCells(bricks);
}

function advanceToNextLevel() {
  // After level 50, stop the game on the final win screen.
  if (level === maxLevel) {
    clearPowerups();
    gameState = "win";
    playSound("win");
    return;
  }

  // Otherwise prepare the next level, then pause briefly before play resumes.
  level++;
  updateLevelDisplay();
  clearPowerups();
  createLevel(level);
  resetBallAndPaddle();
  startLevelCountdown();
}

function startLevelCountdown() {
  // The countdown gives the player a short break before the next level starts.
  gameState = "levelTransition";
  levelCountdownEndTime = Date.now() + levelDelayDuration;
}

function updateLevelCountdown() {
  if (Date.now() >= levelCountdownEndTime) {
    gameState = "playing";
  }
}

// Game Loop
function gameLoop() {
  const currentFrameTime = performance.now();
  const deltaTime = Math.min(currentFrameTime - lastFrameTime, 40);
  lastFrameTime = currentFrameTime;

  // Clear the canvas before drawing the next frame.
  ctx.clearRect(0, 0, canvas.width, canvas.height);

  drawBricks();
  drawBall();
  drawPowerups();
  drawParticles();
  drawFloatingTexts();

  if (gameState !== "paused") {
    updatePaddlePowerup();
    updateParticles(deltaTime);
    updateFloatingTexts(deltaTime);
    movePaddle();
  }

  drawPaddle();
  drawScore();
  drawLevel();
  drawLives();

  // Only update timers, collisions, powerups, and ball movement while playing.
  if (gameState === "playing") {
    checkBrickCollisions();

    if (gameState === "playing") {
      updatePowerups();
      moveBall();
    }
  }

  if (gameState === "start") {
    drawStartScreen();
  } else if (gameState === "levelTransition") {
    updateLevelCountdown();
    drawLevelCountdownScreen();
  } else if (gameState === "paused") {
    drawPausedScreen();
  } else if (gameState === "win") {
    drawWinScreen();
  } else if (gameState === "gameOver") {
    drawGameOverScreen();
  }

  updateActionControls();
  updatePauseControl();

  // Ask the browser to run this function again before the next repaint.
  requestAnimationFrame(gameLoop);
}

createLevel(level);
updateHighScoreDisplay();
lastFrameTime = performance.now();
requestAnimationFrame(gameLoop);
